name: ZAP Fuzzing Scan

on:
  push:
    branches: [ "feature/fuzzing-github" ]
  pull_request:
    branches: [ "main" ]

permissions:
  issues: write
  pull-requests: write

jobs:
  zap-full-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run test web app (готовый контейнер)
        run: |
          docker run -d -p 8080:80 --name test-app strm/helloworld-http
          sleep 10
          curl http://localhost:8080

      - name: Run ZAP Full Scan
        run: |
          docker run --rm -v $(pwd):/zap/wrk:rw \
            --network=host \
            -t ghcr.io/zaproxy/zaproxy:stable \
            zap-full-scan.py \
            -t http://localhost:8080 \
            -r fuzzing_report.html

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: zap-fuzzing-report
          path: fuzzing_report.html