name: ZAP Fuzzing Scan

on:
  push:
    branches: [ "feature/fuzzing-github" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write

jobs:
  zap-full-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and run Spring Boot app
        run: |
          mvn clean package -DskipTests
          nohup java -jar target/*.jar &
          sleep 60

      - name: Run ZAP Full Scan (без автоматической загрузки артефакта)
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:8080'
          fail_action: false
          # artifact_name: 'zap-fuzzing-report'   # отключаем автоматическую загрузку

      - name: Upload ZAP report manually
        uses: actions/upload-artifact@v4
        with:
          name: zap-fuzzing-report
          path: |
            report_html.html
            report_json.json
            report_md.md